/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#f9f9f9",
        "surface-dim": "#dadada",
        "surface-bright": "#f9f9f9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f3",
        "surface-container": "#eeeeee",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "on-surface": "#1b1b1b",
        "on-surface-variant": "#4b4731",
        "inverse-surface": "#303030",
        "inverse-on-surface": "#f1f1f1",
        outline: "#7c775f",
        "outline-variant": "#cdc7aa",
        "surface-tint": "#6a5f00",
        primary: "#6a5f00",
        "on-primary": "#ffffff",
        "primary-container": "#ffe600",
        "on-primary-container": "#726600",
        "inverse-primary": "#dec800",
        secondary: "#0058be",
        "on-secondary": "#ffffff",
        "secondary-container": "#2170e4",
        "on-secondary-container": "#fefcff",
        tertiary: "#b91a24",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#ffddda",
        "on-tertiary-container": "#c4242a",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#fde400",
        "primary-fixed-dim": "#dec800",
        "on-primary-fixed": "#201c00",
        "on-primary-fixed-variant": "#504700",
        "secondary-fixed": "#d8e2ff",
        "secondary-fixed-dim": "#adc6ff",
        "on-secondary-fixed": "#001a42",
        "on-secondary-fixed-variant": "#004395",
        "tertiary-fixed": "#ffdad7",
        "tertiary-fixed-dim": "#ffb3ad",
        "on-tertiary-fixed": "#410004",
        "on-tertiary-fixed-variant": "#930013",
        background: "#f9f9f9",
        "on-background": "#1b1b1b",
        "surface-variant": "#e2e2e2",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["JetBrains Mono", "monospace"],
        mono: ["JetBrains Mono", "monospace"],
      },
      spacing: {
        unit: "4px",
        gutter: "16px",
        "margin-sm": "8px",
        "margin-md": "16px",
        "margin-lg": "24px",
        "window-padding": "20px",
      },
      borderWidth: {
        3: "3px",
        4: "4px",
      },
      boxShadow: {
        brutal: "4px 4px 0px 0px rgba(0,0,0,1)",
        "brutal-lg": "8px 8px 0px 0px rgba(0,0,0,1)",
        "brutal-sm": "2px 2px 0px 0px rgba(0,0,0,1)",
      },
    },
  },
  plugins: [],
};
